### ISSUE TITLE
List iterator and immutability

### ISSUE THREAD

**Issue by mmontone** [bytecurry/colliflower#2]
Hello.

Doesn't it make more sense to implement the list iterator immutably, copying the list? Otherwise, the list is lost when iterating it.

To something like this:

```
(:method ((l list))
    "Iterator for the items of a list, or pairs of an alist."
    (let ((lc (copy-list l)))
    (lambda ()
      (if lc
          (pop lc)
          (end-iteration)))))
```

**Comment by tmccombs** [comment]
The list iterator is immutable as can be tested by the following code:

``` lisp
(let* ((l (list 1 2 3 4 5))
        (it (liter:get-iterator l)))
  (funcall it) ;; returns1
  (funcall it) ;; return 2
  l) ; l is still '(1 2 3 4 5)
```

This works because pop doesn't actually mutate the underlying list. From the CLHS:

> The effect of (pop place) is roughly equivalent to
>  (prog1 (car place) (setf place (cdr place)))

It simply returns the first element of the list and stores a pointer to the rest of the list in the place that was used to access it.
